# Generated by Django 5.2.7 on 2025-11-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_add_slug_to_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
