# Generated by Django 5.2.7 on 2025-11-15 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_subscriber_paystack_reference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-date_posted"],
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
            },
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="category",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="image",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="url",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to auto-assign",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="excerpt",
            field=models.CharField(
                blank=True,
                help_text="Short summary for lists & SEO. Auto-filled from content if empty.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="SEO meta description (max 160 chars)",
                max_length=160,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keywords for SEO",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="source",
            field=models.CharField(
                choices=[
                    ("internal", "WorkBank Team"),
                    ("external", "External Source"),
                    ("guest", "Guest Author"),
                ],
                default="internal",
                max_length=20,
            ),
        ),
    ]
