# Generated by Django 5.2.7 on 2025-11-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_blogpost_options_remove_blogpost_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="paystack_reference",
            field=models.CharField(
                blank=True,
                help_text="Paystack transaction reference (e.g., 123_job)",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
