# Generated by Django 5.2.7 on 2025-11-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_job_paystack_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
